### ISSUE TITLE
Create a TL:DR version or what does this mean for me summary

### ISSUE THREAD

**Issue by SeanCraig** [arctangent-nhsuk/performance-management#2]
To help with engagement maybe distill this

**Comment by arctangent** [comment]
I have fleshed out the Table of Contents to show some appendices and expanded the Introduction to show us calling attention to the Quick Guides as the most relevant starting point.

https://github.com/arctangent-nhsuk/performance-management/commit/52b2f286fef9e18745c62864a477db8ab12a3306
